# Test Pipeline
name: '$(Build.DefinitionName) $(date:yyyyMMdd)$(rev:.r)'

trigger:
- main

pr: 
  branches:
    include:
      - main


workspace:
  clean: 'all'

variables:
  BuildConfiguration: 'Release'
  BuildImage: 'ubuntu-latest'
  TestResultsDirectory: '$(Agent.TempDirectory)/TestResults'
  TestCoverageReportDirectory: '$(Agent.TempDirectory)/coveragereport'
  disable.coverage.autogenerate: 'true'

pool:
  vmImage: '$(BuildImage)'

steps:
- checkout: 'self'
  displayName: 'Check Out Source Code'
  clean: 'true'

- task: UseDotNet@2
  displayName: 'Get .NET SDK'
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- task: DotNetCoreCLI@2
  displayName: 'Restore nuget Packages'
  inputs:
    command: 'restore'
    projects: '/src/*.sln'
    feedsToUse: 'config'
    nugetConfigPath: 'nuget.config'
    verbosityRestore: 'Minimal'

- task: DotNetCoreCLI@2
  displayName: 'Build Projects'
  inputs:
    command: 'build'
    projects: '/src/*.sln'
    arguments: '--no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    configuration: $(BuildConfiguration)
    projects: '**/*[Tt]ests/*Tests.csproj'
    arguments: '--collect:"XPlat Code Coverage" --no-build --no-restore --logger trx --results-directory $(TestResultsDirectory)'
    publishTestResults: false
    testRunTitle: 'Running Unit Tests'

- task: reportgenerator@4
  displayName: 'Generate Code Coverage Report'
  inputs:
    reports: '$(TestResultsDirectory)/**/coverage.cobertura.xml'
    targetdir: '$(TestCoverageReportDirectory)'
    reporttypes: 'HtmlInline_AzurePipelines;Cobertura'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish Code Coverage Report'
  inputs:
    codeCoverageTool: 'Cobertura'
    reportDirectory: '$(TestCoverageReportDirectory)'
    summaryFileLocation: '$(TestCoverageReportDirectory)/Cobertura.xml'
    failIfCoverageEmpty: true

# - task: DotNetCoreCLI@2
#   displayName: 'Publish Projects'
#   inputs:
#     command: 'publish'
#     publishWebProjects: false
#     projects: 'src/**/*.csproj'
#     arguments: '--output $(Build.ArtifactStagingDirectory)'
#     zipAfterPublish: false

# - task: DotNetCoreCLI@2
#   displayName: Pack Projects
#   inputs:
#     command: 'pack'
#     packagesToPack: '**/*.csproj;!**/*.Tests.csproj'
#     versioningScheme: 'off'
#     arguments: '--no-build --no-restore'
#     configuration: $(BuildConfiguration)
#     nobuild: true    

# - task: PublishBuildArtifacts@1
#   displayName: 'Publish Build Artifacts'
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     Parallel: true
#     ArtifactName: 'drop'
#     publishLocation: 'Container'